name: adhd_task_manager
description: A Flutter project for ADHD task management

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_remote_config: ^5.4.2
  firebase_storage: ^12.4.4
  sqflite: ^2.0.0+4
  path_provider: ^2.0.8
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  cloud_functions: ^5.4.0
  google_fonts: ^4.0.4
  animated_background: ^2.0.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - .env

dependency_overrides:
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.5.0
