// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOstcitF3-pizcKG8TH3OOUH8xPy3lkK0',
    appId: '1:716582926052:web:4a25ea30aeebbc5d7e5ef1',
    messagingSenderId: '716582926052',
    projectId: 'adhdtaskmanager-e5706',
    authDomain: 'adhdtaskmanager-e5706.firebaseapp.com',
    storageBucket: 'adhdtaskmanager-e5706.firebasestorage.app',
    measurementId: 'G-1B6MES1NW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZugc5chpvIf9nwuGZzM5UyIozFy0jfU',
    appId: '1:716582926052:android:d9c10f5281c845f17e5ef1',
    messagingSenderId: '716582926052',
    projectId: 'adhdtaskmanager-e5706',
    storageBucket: 'adhdtaskmanager-e5706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvb8ZW-WK9Y6j5LMhHCWQPphRo8H75UQ',
    appId: '1:716582926052:ios:cb396b46a7f00ae27e5ef1',
    messagingSenderId: '716582926052',
    projectId: 'adhdtaskmanager-e5706',
    storageBucket: 'adhdtaskmanager-e5706.firebasestorage.app',
    iosBundleId: 'com.example.adhdTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtvb8ZW-WK9Y6j5LMhHCWQPphRo8H75UQ',
    appId: '1:716582926052:ios:cb396b46a7f00ae27e5ef1',
    messagingSenderId: '716582926052',
    projectId: 'adhdtaskmanager-e5706',
    storageBucket: 'adhdtaskmanager-e5706.firebasestorage.app',
    iosBundleId: 'com.example.adhdTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOstcitF3-pizcKG8TH3OOUH8xPy3lkK0',
    appId: '1:716582926052:web:e516994ed5e6ae3b7e5ef1',
    messagingSenderId: '716582926052',
    projectId: 'adhdtaskmanager-e5706',
    authDomain: 'adhdtaskmanager-e5706.firebaseapp.com',
    storageBucket: 'adhdtaskmanager-e5706.firebasestorage.app',
    measurementId: 'G-WBCQJMQ92P',
  );

}